export interface Branch {
  BicycleParking: string;
  CanGetMoneyTransfer: string;
  CategoryOfWarehouse: string;
  CityDescription: string;
  CityDescriptionRu: string;
  CityRef: string;
  Delivery: { [key: string]: string };
  DenyToSelect: string;
  Description: string;
  DescriptionRu: string;
  Direct: string;
  DistrictCode: string;
  GeneratorEnabled: string;
  InternationalShipping: string;
  Latitude: string;
  Longitude: string;
  MaxDeclaredCost: string;
  Number: string;
  OnlyReceivingParcel: string;
  POSTerminal: string;
  PaymentAccess: string;
  Phone: string;
  PlaceMaxWeightAllowed: string;
  PostFinance: string;
  PostMachineType: string;
  PostalCodeUA: string;
  ReceivingLimitationsOnDimensions: {
    Width: number;
    Height: number;
    Length: number;
  };
  Reception: { [key: string]: string };
  Ref: string;
  RegionCity: string;
  Schedule: { [key: string]: string };
  SelfServiceWorkplacesCount: string;
  SendingLimitationsOnDimensions: {
    Width: number;
    Height: number;
    Length: number;
  };
  SettlementAreaDescription: string;
  SettlementDescription: string;
  SettlementRef: string;
  SettlementRegionsDescription: string;
  SettlementTypeDescription: string;
  SettlementTypeDescriptionRu: string;
  ShortAddress: string;
  ShortAddressRu: string;
  SiteKey: string;
  TotalMaxWeightAllowed: string;
  TypeOfWarehouse: string;
  WarehouseForAgent: string;
  WarehouseIndex: string;
  WarehouseStatus: string;
  WarehouseStatusDate: string;
  WorkInMobileAwis: string;
}